winget install --id M2Team.NanaZip
winget install --id Adobe.CreativeCloud 
winget install --id Microsoft.PowerToys
winget install --id GodotEngine.GodotEngine
winget install --id Git.Git
winget install --id Golang.Go
winget install --id Microsoft.VisualStudio.2022.Community
winget install --id Anysphere.Cursor
winget install --id Microsoft.PowerShell
winget install --id Microsoft.VisualStudioCode
winget install --id SublimeHQ.SublimeMerge
winget install --id SublimeHQ.SublimeText.4
winget install --id Obsidian.Obsidian
winget install --id EliasFotinis.DeskPins
winget install --id Daum.PotPlayer
winget install --id Piriform.Speccy
winget install --id Valve.Steam
winget install --id JAMSoftware.TreeSize.Free
winget install --id Unity.UnityHub
winget install --id BillStewart.SyncthingWindowsSetup